config/routes.rb
Rails.application.routes.draw do

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
 
  get :login , path: '/saimalworld/login', to: 'login#login'
  post :sign_in , to: 'login#sign_in'
  resources :users
  resources :products 
  # Defines the root path route ("/")
  root "home#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/models/payment_detail.rb
class PaymentDetail < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/shopping_session.rb
class ShoppingSession < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
 has_secure_password
 validates :name, presence: true, uniqueness: true
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
end

app/models/user_payment.rb
class UserPayment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
  
    def current_user
      # If session[:user_id] is nil, set it to nil, otherwise find the user by id.
      @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
    end
end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home
        
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login
    @user = User.new
  end

  def sign_in
    @user = User.find_by(name: params[:user][:name])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "Login failed"
      redirect_to login_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = "Product created successfully"
      redirect_to products_path
    else
      flash[:alert] = "Product not created"
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @product = Product.find_by(id: params[:id])

    if @product.update(product_params)
      flash[:notice] = "Product updated successfully."
      redirect_to products_path
    else
      flash[:alert] = "Product not created."
      render :new, status: :unprocessable_entity
    end
  end
  
  def show
  end

  def edit
    @product = Product.find_by(id: params[:id])
  end

  private

  def product_params
    params.require(:product).permit(:product_name, :desc, :sku, :category_id, :inventory_id, :price, :discount_id, :created_at, :updated_at)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "User created successfully"
      redirect_to users_path
    else
      flash[:alert] = "User not created"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/home.html.erb
<p>Saimal Shopping Site</p>

<% if current_user %>
  <h1>Welcome, <%= current_user.name %></h1>
  <%=link_to 'Add Product', new_product_path %>
  <%=link_to 'show Product', products_path %>
<% else %>
  <h1>This is the index page</h1>
  <%= link_to 'Login', login_path %><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Saimal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>

  <%= yield %>
  </div>
  <div class="col-md-4"></div>
  </div>
</body>

</html>

app/views/login/destroy.html.erb
<h1>Sessions#destroy</h1>
<p>Find me in app/views/sessions/destroy.html.erb</p>

app/views/login/login.html.erb
<h1>Login page</h1>
<%= form_with model: @user, url: sign_in_path do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <p>
    <%= f.submit 'Login' %>
  </p>
<% end %>

app/views/login/sign_in.html.erb
<h1>Sessions#create</h1>
<p>Find me in app/views/sessions/create.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#new</h1>
<%= form_with model: @product do |f| %>
  <% if @product.errors.any? %>
    <div>
      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :desc %>
  </div>
  <div>
    <%= f.label :sku %><br>
    <%= f.text_field :sku %>
  </div>
  <div>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/index.html.erb
<h1>Products#index</h1>

<%=link_to 'show Product', new_product_path %>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Edit</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.product_name %></td>
        <td><%= link_to 'Edit', edit_product_path(id: product.id)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>Products#new</h1>
<%= form_with model: @product do |f| %>
  <% if @product.errors.any? %>
    <div>
      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :desc %>
  </div>
  <div>
    <%= f.label :sku %><br>
    <%= f.text_field :sku %>
  </div>
  <div>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

app/views/users/index.html.erb
<!-- app/views/users/index.html.erb -->
<h1>Users#index</h1>

<%= link_to 'New User', new_user_path %>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>name</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Users#new</h1>
<%= form_with model: @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>